# Generated by Django 4.1.1 on 2023-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_email_alter_user_age_range_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_nickname',
        ),
    ]
