# Generated by Django 4.1.4 on 2022-12-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceRestAPI', '0002_ticket_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='performance_info',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
