# Generated by Django 4.1.4 on 2022-12-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceRestAPI', '0003_ticket_performance_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='performance_info',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
